import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <Header />
        </div>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
